export const RESET_STATE = 'RESET_STATE';
export const FETCH_SEARCH_RESULTS_STARTED = 'FETCH_SEARCH_RESULTS_STARTED';
export const FETCH_SEARCH_RESULTS_FINISHED_SUCCESS =
  'FETCH_SEARCH_RESULTS_FINISHED_SUCCESS';
export const FETCH_SEARCH_RESULTS_FINISHED_ERROR =
  'FETCH_SEARCH_RESULTS_FINISHED_ERROR';
export const SEARCH_PARAM_CHANGED = 'SEARCH_PARAM_CHANGED';
export const SEARCH_SORT_CHANGED = 'SEARCH_SORT_CHANGED';
export const FETCH_TOTAL_COMMENTS_FINISHED_SUCCESS =
  'FETCH_TOTAL_COMMENTS_FINISHED_SUCCESS';
export const MAX_RESULTS_CHANGED = 'MAX_RESULTS_CHANGED';
